apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: default
  name: save-result
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: write-file
            image: tsmcting/crawler:1.0.0
            volumeMounts:
            - name: history-dir
              mountPath: /var/log/history
          restartPolicy: OnFailure
          volumes:
          - name: history-dir
            persistentVolumeClaim:
              claimName: pvc-demo
